# Standalone file: do not edit by hand
# Source: https://github.com/elipousson/standaloner/blob/HEAD/R/standalone-extra-checks.R
# Generated by: usethis::use_standalone("elipousson/standaloner", "extra-checks")
# ----------------------------------------------------------------------
#
# ---
# repo: elipousson/standaloner
# file: standalone-extra-checks.R
# last-updated: 2026-09-17
# license: https://opensource.org/license/mit/
# imports: [rlang (>= 1.1.0), cli (>= 2.5.0)]
# ---
#
# Note: the functions in this script depend on functions from
# `standalone-types-check.R` but does not import the script directly. If you use
# this script, you must run `usethis::use_standalone("r-lib/rlang",
# "types-check")` first for these additional checks to work as expected.
#
# ## Changelog
#
# 2026-09-17:
# * Update minimum rlang version to >= 1.1.0 to match standalone-types-check.R`.
# * Fix `check_list()` erroring instead of validating when `allow_na = TRUE`
#   and `x` is `NULL`, an empty list, or has length != 1 (the unguarded
#   `is.na(x)` call assumed a length-1 input).
# * Fix `check_exclusive_args()` reporting a false positive ("exactly one
#   must be supplied") when `x` or `y` is a vector of length >= 2, by
#   checking `NULL`-ness of each argument directly instead of the combined
#   length of `c(x, y)`.
# * Add `allow_only` argument to `check_has_name()` to error if `x` has any
#   names other than `nm`, comparable to `testthat::expect_named(exact =
#   TRUE)`.
# * Fix `check_inherits_all()` error message wording, which reused
#   `check_inherits_any()`'s "or"-joined list of classes even though it
#   requires all of them; multiple classes are now joined with "and".
# * Remove explicit `rlang::` namespacing from all functions in this script
#   to match the unprefixed convention already used by
#   `standalone-types-check.R` (avoids onLoad issues per r-lib/rlang#1482).
# * Fix `is_url()`'s `url_pattern` regex: an unescaped `-` in `[$-_@.&+]`
#   formed an unintended range covering ASCII 36-95 (silently accepting
#   backslash, angle brackets, semicolon, `%`, `=`, `?`, `:`, `/`, etc. as
#   "valid" URL characters), and `[!*\\(\\),]` escaped `(`/`)` unnecessarily
#   inside a bracket expression (backslash isn't special there), which added
#   a stray literal backslash to that class too. Rewrote as separate,
#   unambiguous character classes and added an explicit `[][]` class so
#   IPv6 literal hosts (e.g. `https://[::1]/`) - only matched before by
#   the same range bug - are still recognized on purpose.
#
# 2024-02-06:
# * Fix issue with passing unavailable dots. Add dots more consistently.
#
# 2023-10-10:
# * Rename package from settoken to more general name: standaloner.
#
# 2023-09-29:
# * Create file with `check_list()`, `is_url()`, `check_url()`,
# `check_inherits_any()`, `check_inherits_all()`, and `check_exclusive_args()`
#
# nocov start

#' Check if object is a list
#'
#' @noRd
check_list <- function(
  x,
  allow_na = FALSE,
  allow_empty = FALSE,
  allow_null = FALSE,
  arg = caller_arg(x),
  call = caller_env()
) {
  if (allow_na && length(x) == 1 && is.na(x)) {
    return(invisible(NULL))
  }

  if (allow_null && is_null(x)) {
    return(invisible(NULL))
  }

  if (is_empty(x)) {
    if (allow_empty) {
      return(invisible(NULL))
    }

    cli_abort(
      "{.arg {arg}} can't be empty.",
      call = call
    )
  }

  if (is_list(x)) {
    return(invisible(NULL))
  }

  stop_input_type(
    x,
    what = "a list",
    arg = arg,
    call = call
  )
}

#' Does x match the pattern of a URL?
#' @noRd
is_url <- function(x, pattern = NULL, ...) {
  if (!is_vector(x) || is_empty(x)) {
    return(FALSE)
  }

  url_pattern <- "http[s]?://(?:[[:alnum:]]|[$_@.&+-]|[!*(),]|[][]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"

  if (is.null(pattern)) {
    return(grepl(url_pattern, x, ...))
  }

  grepl(url_pattern, x, ...) & grepl(pattern, x, ...)
}


#' Check is a URL is valid
#' @noRd
check_url <- function(
  url,
  pattern = NULL,
  ...,
  allow_null = FALSE,
  arg = caller_arg(url),
  call = caller_env()
) {
  if (allow_null && is_null(url)) {
    return(invisible(NULL))
  }

  if (is_url(url, pattern = pattern)) {
    return(invisible(NULL))
  }

  check_string(
    url,
    allow_empty = FALSE,
    allow_null = allow_null,
    arg = arg,
    call = call
  )

  stop_input_type(
    url,
    what = "a valid url",
    ...,
    arg = arg,
    call = call
  )
}

#' Check if x inherits any of the supplied class values and error if not
#' @inheritParams rlang::inherits_any
#' @noRd
check_inherits_any <- function(
  x,
  class,
  ...,
  allow_null = FALSE,
  arg = caller_arg(x),
  call = caller_env()
) {
  if (allow_null && is.null(x)) {
    return(invisible(NULL))
  }

  if (inherits_any(x, class)) {
    return(invisible(NULL))
  }

  stop_input_type(
    x,
    what = class,
    ...,
    arg = arg,
    call = call
  )
}

#' Check if x inherits all of the supplied class values and error if not
#' @inheritParams rlang::inherits_any
#' @noRd
check_inherits_all <- function(
  x,
  class,
  ...,
  allow_null = FALSE,
  arg = caller_arg(x),
  call = caller_env()
) {
  if (allow_null && is.null(x)) {
    return(invisible(NULL))
  }

  if (inherits_all(x, class)) {
    return(invisible(NULL))
  }

  what <- class

  if (length(class) > 1) {
    what <- paste(class, collapse = " and ")
  }

  stop_input_type(
    x,
    what = what,
    ...,
    arg = arg,
    call = call
  )
}

#' Check if x or y is not `NULL` and error if neither or both are supplied
#' @inheritParams rlang::check_exclusive
#' @noRd
check_exclusive_args <- function(
  x = NULL,
  y = NULL,
  require = TRUE,
  ...,
  x_arg = caller_arg(x),
  y_arg = caller_arg(y),
  call = caller_env()
) {
  has_x <- !is_null(x)
  has_y <- !is_null(y)

  if (!has_x && !has_y) {
    if (!require) {
      return(invisible(NULL))
    }

    cli_abort(
      "One of {.arg {x_arg}} or {.arg {y_arg}} must be supplied.",
      call = call,
      ...
    )
  }

  if (has_x && has_y) {
    cli_abort(
      "Exactly one of {.arg {x_arg}} or {.arg {y_arg}} must be supplied.",
      call = call,
      ...
    )
  }

  invisible(NULL)
}

#' Check if x has names
#' @noRd
check_has_name <- function(
  x,
  nm,
  ...,
  allow_any = FALSE,
  allow_only = FALSE,
  allow_null = FALSE,
  arg = caller_arg(x),
  call = caller_env()
) {
  check_required(x, arg = arg, call = call)

  if (allow_null && is.null(x)) {
    return(invisible(NULL))
  }

  check_character(nm, call = call)

  has_nm <- has_name(x, nm)

  if (allow_only) {
    extra_nm <- setdiff(names2(x), nm)
    extra_nm <- extra_nm[extra_nm != ""]

    if (all(has_nm) && length(extra_nm) == 0) {
      return(invisible(NULL))
    }

    add_msg <- NULL

    if (any(!has_nm)) {
      add_msg <- c(
        add_msg,
        "i" = "{.arg {arg}} is missing {.val {nm[!has_nm]}}"
      )
    }

    if (length(extra_nm) > 0) {
      add_msg <- c(
        add_msg,
        "i" = "{.arg {arg}} has extra name{cli::qty(length(extra_nm))}{?s} {.val {extra_nm}}"
      )
    }

    cli_abort(
      message = c(
        "{.arg {arg}} must have only the name{cli::qty(length(nm))}{?s} {.val {nm}}.",
        add_msg
      ),
      ...,
      .envir = current_env(),
      call = call
    )
  }

  if (all(has_nm)) {
    return(invisible(NULL))
  }

  if (allow_any && any(has_nm)) {
    return(invisible(NULL))
  }

  n <- length(nm)
  what <- " all of"
  add_msg <- c("i" = "{.arg {arg}} is missing {.val {nm[!has_nm]}}")

  if (n == 1) {
    what <- ""
    add_msg <- NULL
  } else if (allow_any) {
    what <- " any of"
    add_msg <- NULL
  }

  cli_abort(
    message = c(
      "{.arg {arg}} must have{what} the name{cli::qty(n)}{?s} {.val {nm}}.",
      add_msg
    ),
    ...,
    .envir = current_env(),
    call = call
  )
}

# nocov end
